# Functions

In [1]:
name = 'serge rey'

In [2]:
name.upper()

'SERGE REY'

In [3]:
type(name)

str

In [4]:
numbers = range(10)

In [5]:
numbers

range(0, 10)

In [6]:
max(numbers)

9

In [7]:
max?

In [8]:
max(name)

'y'

In [9]:
# write a function to square an integer

def square(x):
    x2 = x * x
    x2 = x**2

In [10]:
square(5)

In [11]:
def square(x):
    x2 = x**2
    return x2

In [12]:
square(5)

25

In [13]:
def square(x):
    return x*x

In [14]:
square(3)

9

In [15]:
def power(base, exponent):
    return base**exponent

In [16]:
power(3, 2)

9

In [17]:
power(2, 3)

8

In [18]:
def power(base, exponent=2):
    return base**exponent

In [19]:
power(2, 3)

8

In [20]:
power(2)

4

In [21]:
power(2, 5)

32

In [22]:
def power(base=4, exponent=2):
    """This is our power function that raises
    
    base: base value
    to an
    exponent"""
    return base**exponent

In [23]:
power()

16

In [24]:
power??

In [25]:
power(exponent=3, base=10)

1000

In [26]:
power()

16

In [27]:
import csv
newlines = []
with open('data/airports.csv', 'r') as f:
    reader = csv.reader(f)
    for line in reader:
        newlines.append(line)

In [28]:
def read_csv(file_name):
    newlines = []
    with open(file_name, 'r') as f:
        reader = csv.reader(f)
        for line in reader:
            newlines.append(line)
    return newlines

In [29]:
data = read_csv('data/airports.csv')

In [30]:
def get_attribute(data, attribute_name):
    header = data[0]
    idx = header.index(attribute_name)
    return [record[idx] for record in data[1:]]

In [31]:
get_attribute(data, 'latitude')

['-6.081689',
 '-5.207083',
 '-5.826789',
 '-6.569828',
 '-9.443383',
 '-3.583828',
 '61.160517',
 '64.190922',
 '67.016969',
 '76.531203',
 '65.659994',
 '65.283333',
 '64.295556',
 '65.952328',
 '66.058056',
 '63.985',
 '65.555833',
 '64.13',
 '66.133333',
 '63.424303',
 '46.485001',
 '50.056389',
 '44.639721',
 '51.391944',
 '49.082222',
 '68.534444',
 '49.1325',
 '48.330555',
 '64.298889',
 '49.950832',
 '49.91',
 '69.108055',
 '49.052333',
 '49.296389',
 '47.007778',
 '47.990833',
 '67.816667',
 '52.075001',
 '49.152779',
 '70.486111',
 '64.193333',
 '64.043056',
 '61.371111',
 '49.468056',
 '49.210833',
 '58.422222',
 '51.100834',
 '55.742333',
 '53.309723',
 '61.094166',
 '49.210278',
 '53.578888',
 '79.994722',
 '68.304167',
 '63.75639',
 '45.868889',
 '48.746111',
 '54.678055',
 '61.180832',
 '61.760153',
 '44.225277',
 '53.625278',
 '48.775278',
 '49.778332',
 '47.424721',
 '52.816666',
 '49.831667',
 '70.762778',
 '68.635556',
 '43.173611',
 '45.5175',
 '60.839722',
 '44.880833',
 '48.773888',
 '72.683334',
 '45.294445',
 '48.544167',
 '50.702222',
 '43.460833',
 '54.805278',
 '51.5175',
 '43.862221',
 '47.82',
 '54.125278',
 '53.309166',
 '82.517778',
 '49.956112',
 '63.616389',
 '50.330278',
 '56.653333',
 '51.291111',
 '46.272778',
 '45.681944',
 '50.19',
 '45.521694',
 '49.761667',
 '67.570556',
 '54.404999',
 '58.621389',
 '45.3225',
 '53.214167',
 '56.226944',
 '49.903056',
 '49.21611',
 '51.446388',
 '49.836389',
 '44.23',
 '54.28611',
 '58.767223',
 '44.974722',
 '46.791111',
 '52.182222',
 '42.275556',
 '60.116389',
 '49.788334',
 '49.630278',
 '46.112221',
 '49.710833',
 '50.431944',
 '48.371944',
 '55.179722',
 '51.264721',
 '52.769167',
 '48.936944',
 '46.161388',
 '53.026112',
 '74.716944',
 '47.764444',
 '48.52',
 '52.429722',
 '62.81139',
 '46.625',
 '45.438611',
 '45.316111',
 '60.020278',
 '72.982222',
 '46.440556',
 '71.993889',
 '64.23',
 '55.801111',
 '44.118889',
 '48.569721',
 '43.627499',
 '69.433334',
 '45.470556',
 '66.521389',
 '68.776111',
 '48.206111',
 '55.15139',
 '53.355833',
 '67.545833',
 '48.053333',
 '58.096111',
 '65.281617',
 '49.193889',
 '55.841944',
 '44.745834',
 '45.952221',
 '49.910036',
 '52.921944',
 '52.183056',
 '63.209444',
 '49.612222',
 '53.5725',
 '52.170834',
 '50.01889',
 '56.238056',
 '50.113889',
 '66.145',
 '47.695',
 '53.889444',
 '54.468508',
 '43.033056',
 '49.025278',
 '60.709553',
 '46.363611',
 '51.113888',
 '54.824722',
 '58.836389',
 '49.463056',
 '46.290001',
 '69.546667',
 '48.646944',
 '56.863888',
 '50.291944',
 '58.739167',
 '53.319168',
 '47.61861',
 '49.413889',
 '50.290279',
 '48.608612',
 '43.677223',
 '43.7425',
 '45.885277',
 '62.462778',
 '55.293056',
 '53.254333',
 '42.999444',
 '50.680556',
 '54.14389',
 '50.223333',
 '60.172779',
 '44.984444',
 '62.2075',
 '67.4075',
 '36.503613',
 '35.3325',
 '36.711997',
 '36.691014',
 '24.292767',
 '36.545834',
 '26.710103',
 '26.723536',
 '35.525414',
 '22.811461',
 '36.795136',
 '33.535853',
 '35.752239',
 '36.822225',
 '36.276028',
 '35.431611',
 '32.930431',
 '35.341136',
 '35.735389',
 '27.700372',
 '36.212658',
 '35.542444',
 '35.016667',
 '35.623858',
 '35.171775',
 '35.207725',
 '27.837589',
 '34.793289',
 '30.571294',
 '32.384106',
 '31.672972',
 '27.251022',
 '33.067803',
 '33.764383',
 '29.237119',
 '31.917223',
 '28.05155',
 '6.357228',
 '12.353194',
 '11.160056',
 '5.605186',
 '9.557192',
 '10.082664',
 '7.361828',
 '4.896056',
 '5.261386',
 '7.7388',
 '6.792808',
 '9.387183',
 '7.272069',
 '4.746717',
 '6.903167',
 '9.006792',
 '7.246739',
 '6.316981',
 '4.976019',
 '6.474272',
 '12.171667',
 '7.362458',
 '8.440211',
 '9.639828',
 '10.696025',
 '12.047589',
 '11.855347',
 '7.703883',
 '6.577369',
 '9.652172',
 '5.015494',
 '12.916322',
 '9.257553',
 '11.130192',
 '13.502531',
 '13.481547',
 '14.875658',
 '16.965997',
 '18.968703',
 '13.372894',
 '13.778997',
 '35.758056',
 '36.851033',
 '37.245447',
 '32.306156',
 '34.422022',
 '33.876919',
 '36.721339',
 '33.875031',
 '31.704281',
 '34.717953',
 '33.939722',
 '9.767333',
 '6.165611',
 '51.189444',
 '50.75861',
 '51.168333',
 '50.901389',
 '49.891667',
 '50.459197',
 '50.575833',
 '51.090278',
 '50.243333',
 '50.817222',
 '50.637417',
 '51.198889',
 '50.9475',
 '50.791944',
 '50.035833',
 '51.144133',
 '51.394783',
 '51.264722',
 '51.193531',
 '50.981817',
 '51.831828',
 '52.197333',
 '39.6335556',
 '51.308111',
 '51.363',
 '51.552',
 '51.2935',
 '53.306417',
 '52.579978',
 '52.203258',
 '54.33754',
 '50.915161',
 '52.918833',
 '52.073658',
 '51.363167',
 '53.8327',
 '51.889475',
 '51.29625',
 '52.380001',
 '51.132767',
 '50.979811',
 '50.026421',
 '52.134642',
 '53.630389',
 '52.473025',
 '50.865917',
 '51.289453',
 '48.353783',
 '49.4987',
 '51.432447',
 '49.214553',
 '48.689878',
 '52.559686',
 '52.461056',
 '53.0475',
 '49.960833',
 '49.948672',
 '49.472706',
 '51.034878',
 '49.606511',
 '49.968931',
 '50.992797',
 '50.707658',
 '53.535886',
 '54.3795',
 '53.805367',
 '50.405888',
 '51.099445',
 '51.483333',
 '51.402333',
 '51.964833',
 '51.230356',
 '51.614089',
 '51.995844',
 '51.518314',
 '48.425158',
 '48.111',
 '48.396167',
 '48.108833',
 '48.081364',
 '48.90095',
 '48.635167',
 '47.859117',
 '47.671317',
 '53.426997',
 '52.627778',
 '48.777833',
 '49.984428',
 '49.793833',
 '50.288836',
 '50.018',
 '50.3255',
 '49.8635',
 '49.302776',
 '49.209525',
 '47.973331',
 '48.022653',
 '48.053833',
 '49.118317',
 '51.6075',
 '52.319167',
 '51.408394',
 '52.179833',
 '53.507081',
 '53.391186',
 '53.271592',
 '53.504833',
 '53.5955',
 '53.706822',
 '54.771772',
 '54.220928',
 '54.91325',
 '59.260286',
 '58.990756',
 '58.229883',
 '58.419044',
 '59.413317',
 '58.307461',
 '68.362586',
 '61.116112',
 '61.85605',
 '60.254558',
 '60.317222',
 '61.689656',
 '59.848864',
 '60.654444',
 '60.462502',
 '61.249172',
 '62.166111',
 '68.607269',
 '62.662906',
 '62.399453',
 '63.127078',
 '65.781889',
 '64.285472',
 '62.462502',
 '63.721172',
 '66.712883',
 '65.987575',
 '67.701022',
 '63.00715',
 '61.144158',
 '61.044553',
 '60.122203',
 '62.946667',
 '61.6866',
 '60.333889',
 '64.930061',
 '61.245558',
 '61.461686',
 '65.402222',
 '63.731917',
 '64.688056',
 '62.065481',
 '66.564822',
 '60.744722',
 '61.943064',
 '61.062389',
 '67.395033',
 '61.414147',
 '61.77335',
 '60.514142',
 '60.896394',
 '63.05065',
 '62.171111',
 '64.060547',
 '54.6575',
 '54.398889',
 '54.618056',
 '55.042778',
 '52.453856',
 '52.369722',
 '52.607778',
 '51.894167',
 '52.5175',
 '51.668056',
 '52.040833',
 '52.192222',
 '53.353744',
 '53.338056',
 '51.087167',
 '50.440558',
 '51.505144',
 '51.152189',
 '50.086092',
 '51.404811',
 '51.009358',
 '51.833056',
 '51.396667',
 '51.605333',
 '51.382669',
 '53.333611',
 '51.874722',
 '50.422778',
 '50.78',
 '50.950261',
 '51.187167',
 '49.706111',
 '49.434956',
 '49.207947',
 '50.835556',
 '51.330833',
 '51.148056',
 '51.505278',
 '51.275833',
 '51.676111',
 '51.323889',
 '51.4775',
 '51.571389',
 '50.956111',
 '51.342222',
 '53.719667',
 '54.9375',
 '53.280556',
 '53.771667',
 '53.574444',
 '54.131167',
 '53.865897',
 '53.745097',
 '53.178056',
 '54.083333',
 '55.0375',
 '54.509189',
 '52.831111',
 '52.811744',
 '52.871164',
 '52.798169',
 '53.581575',
 '58.957778',
 '59.878889',
 '58.458889',
 '57.201944',
 '57.5425',
 '55.871944',
 '55.95',
 '55.681944',
 '55.509444',
 '57.481111',
 '60.432778',
 '56.452499',
 '58.215556',
 '56.499167',
 '56.372889',
 '57.705214',
 '52.205',
 '52.468056',
 '52.675833',
 '51.885',
 '51.721667',
 '53.394256',
 '52.072222',
 '50.734444',
 '51.519444',
 '51.836944',
 '51.616389',
 '52.409333',
 '52.361933',
 '52.127283',
 '52.357167',
 '51.682167',
 '51.749964',
 '51.234139',
 '52.640028',
 '51.553',
 '53.093014',
 '54.137186',
 '54.292383',
 '53.834333',
 '52.342611',
 '52.735711',
 '53.307778',
 '52.612558',
 '54.048911',
 '53.166167',
 '54.205522',
 '53.03035',
 '52.962225',
 '52.648353',
 '-51.822777',
 '52.308613',
 '51.25528',
 '50.911658',
 '52.060556',
 '53.119167',
 '51.450139',
 '53.11972',
 '51.567389',
 '52.923353',
 '52.460278',
 '53.228611',
 '51.956944',
 '52.1273',
 '52.27',
 '52.166139',
 '51.449092',
 '51.841269',
 '53.300175',
 '53.421333',
 '53.910297',
 '52.180878',
 '53.301667',
 '52.701978',
 '54.280214',
 '52.1872',
 '56.300017',
 '55.740322',
 '55.617917',
 '55.525942',
 '55.941387',
 '56.297458',
 '57.277228',
 '54.699344',
 '55.476664',
 '54.870306',
 '55.585567',
 '55.063267',
 '54.964367',
 '55.225553',
 '56.550208',
 '57.0688',
 '55.436283',
 '62.063628',
 '56.846944',
 '55.990122',
 '57.092789',
 '49.626575',
 '62.560372',
 '69.2925',
 '69.976111',
 '60.63885',
 '65.461111',
 '67.269167',
 '60.293386',
 '70.600278',
 '58.204214',
 '60.416667',
 '69.055758',
 '68.4913',
 '61.015556',
 '61.583611',
 '60.193917',
 '59.345267',
 '70.486675',
 '63.111781',
 '59.969336',
 '69.725781',
 '58.099486',
 '62.744722',
 '65.783997',
 '70.068814',
 '59.565683',
 '63.698908',
 '62.578411',
 '59.378933',
 '78.246111',
 '59.185',
 '59.791925',
 '65.956828',
 '69.683333',
 '59.186703',
 '63.457556',
 '58.876778',
 '52.268494',
 '54.377569',
 '50.077731',
 '50.238147',
 '50.474253',
 '50.322275',
 '52.421031',
 '50.109958',
 '53.584731',
 '54.478889',
 '53.790639',
 '52.16575',
 '51.102683',
 '52.138517',
 '58.402278',
 '58.610867',
 '59.897328',
 '56.266667',
 '58.498136',
 '57.662836',
 '57.757594',
 '58.169794',
 '58.465522',
 '57.774722',
 '58.4564',
 '58.318056',
 '58.513842',
 '58.426445',
 '59.418694',
 '59.345867',
 '60.957908',
 '58.788636',
 '59.675856',
 '56.610761',
 '56.950278',
 '55.921686',
 '55.944444',
 '57.350453',
 '57.264167',
 '56.685531',
 '55.530193',
 '56.691128',
 '57.292222',
 '56.929144',
 '63.738333',
 '62.408889',
 '62.047811',
 '67.132408',
 '61.768092',
 '66.496236',
 '63.048597',
 '64.548322',
 '63.128611',
 '62.528125',
 '63.408339',
 '65.398333',
 '67.821986',
 '61.190033',
 '64.624772',
 '62.481369',
 '63.791828',
 '64.579083',
 '65.590278',
 '59.223733',
 '59.589444',
 '65.543758',
 '65.875325',
 '59.386585',
 '59.651944',
 '59.354372',
 '60.422017',
 '57.525833',
 '60.593333',
 '58.40615',
 '58.586253',
 '59.351078',
 '57.662797',
 '67.764789',
 '49.972667',
 '49.436911',
 '49.920433',
 '49.648131',
 '52.2785',
 '52.5912',
 '52.291167',
 '51.1145',
 '48.220297',
 '50.366',
 '49.391833',
 '49.2175',
 '52.919406',
 '49.698686',
 '50.169189',
 '49.218056',
 '49.743057',
 '53.767667',
 '52.585514',
 '50.960817',
 '54.312167',
 '53.5335',
 '53.918167',
 '50.831167',
 '54.459333',
 '53.547833',
 '53.602167',
 '52.457333',
 '49.63361',
 '49.563569',
 '50.049819',
 '48.0705',
 '50.173833',
 '48.322333',
 '48.205667',
 '51.767833',
 '48.715667',
 '48.1855',
 '48.711',
 '51.922833',
 '-28.575001',
 '-29.281767',
 '-26.23865',
 '-32.89715',
 '-29.092722',
 '-28.248392',
 '-27.366769',
 '-33.964806',
 '-31.500278',
 '-29.970089',
 '-33.035569',
 '-26.495644',
 '-28.823119',
 '-25.986267',
 '-34.005553',
 '-32.193611',
 '-33.284721',
 '-29.122011',
 '-28.078694',
 '-28.235072',
 '-24.368642',
 '-30.562164',
 '-26.139166',
 '-26.871064',
 '-28.802834',
 '-26.080978',
 '-27.660617',
 '-27.456667',
 '-29.688403',
 '-25.938514',
 '-26.175672',
 '-23.159911',
 '-32.968889',
 '-28.581667',
 '-25.684775',
 '-30.857408',
 '-24.989114',
 '-27.079253',
 '69.2225',
 '-25.473603',
 '-25.704458',
 '-27.626086',
 '-27.770586',
 '-24.686056',
 '-34.554861',
 '-33.606967',
 '-33.984919',
 '-34.090279',
 '-23.937166',
 '-23.926089',
 '-31.605886',
 '-29.648975',
 '-25.333822',
 '-23.845306',
 '-26.670994',
 '-26.889344',
 '-31.920197',
 '-28.741039',
 '-25.6443',
 '-33.812181',
 '-29.689333',
 '-26.524083',
 '-32.964067',
 '-26.248411',
 '-25.809717',
 '-27.648606',
 '-34.048222',
 '-24.960944',
 '-28.260028',
 '-29.032928',
 '-26.776556',
 '-23.824417',
 '-28.320586',
 '-28.399097',
 '-31.547903',
 '-26.982408',
 '-29.770606',
 '-31.640961',
 '-26.566372',
 '-25.653858',
 '-25.832294',
 '-25.83',
 '-27.998',
 '-33.900244',
 '-25.598972',
 '-21.159597',
 '-24.602333',
 '-17.832875',
 '-19.972564',
 '-24.555225',
 '-22.05835',
 '-4.2517',
 '-0.53135',
 '1.615994',
 '-4.816028',
 '-26.529022',
 '4.398475',
 '4.221583',
 '1.905469',
 '3.755267',
 '-7.969597',
 '-20.430235',
 '-19.757658',
 '-7.313267',
 '4.089192',
 '4.006081',
 '10.451392',
 '5.636919',
 '7.357011',
 '9.335892',
 '5.536919',
 '6.039239',
 '3.836039',
 '-12.572778',
 '-17.821756',
 '-15.330817',
 '-13.258878',
 '-15.254542',
 '-12.998139',
 '-12.900469',
 '-11.533661',
 '-12.298108',
 '-12.131667',
 '-12.804722',
 '-20.8871',
 '-21.320039',
 '-18.79695',
 '-19.562778',
 '-17.093889',
 '-18.109517',
 '-20.28475',
 '-12.3494',
 '-16.1639',
 '-14.651667',
 '-13.188431',
 '-14.999411',
 '-14.629694',
 '-15.667144',
 '-13.312067',
 '-16.741945',
 '-15.436666',
 '-14.278611',
 '-13.375834',
 '-14.89875',
 '-13.484814',
 '-25.038056',
 '-21.441558',
 '-22.805286',
 '-22.119722',
 '-21.201772',
 '-21.753867',
 '-23.383369',
 '-6.269897',
 '-12.609025',
 '-5.596992',
 '18.3127',
 '-12.808878',
 '-12.404633',
 '-12.371233',
 '-8.858375',
 '-9.525086',
 '-14.657583',
 '-7.754506',
 '-10.721956',
 '-9.689067',
 '-6.141086',
 '-14.924733',
 '-11.768086',
 '-7.603067',
 '-16.755417',
 '1.543108',
 '-0.665214',
 '-0.704389',
 '2.075639',
 '-0.711739',
 '-1.574733',
 '0.579211',
 '0.4586',
 '-1.656156',
 '1.662936',
 '0.378175',
 '-19.796419',
 '-23.876431',
 '-13.273986',
 '-15.033058',
 '-25.920836',
 '-11.672922',
 '-11.361789',
 '-13.225053',
 '-14.488233',
 '-15.105611',
 '-12.986753',
 '-17.8555',
 '-15.602694',
 '-16.104817',
 '-14.704617',
 '-22.018431',
 '-7.004783',
 '-5.696697',
 '-10.109611',
 '-4.674342',
 '-4.319292',
 '-7.134567',
 '13.847',
 '8.624406',
 '12.133689',
 '17.917053',
 '-20.017431',
 '-17.751561',
 '-21.008083',
 '-18.095881',
 '-17.931806',
 '-16.519761',
 '-17.431917',
 '-18.997499',
 '-20.055333',
 '-20.289497',
 '-19.436394',
 '-18.629872',
 '-15.679053',
 '-9.953569',
 '-13.014631',
 '-13.789378',
 '-11.44475',
 ...]

In [32]:
def to_float(attribute_list):
    return list(map(float, attribute_list))

In [33]:
flat = to_float(get_attribute(data, 'latitude'))

In [34]:
min_lat = min(flat)
min_lat

-89.999997

In [35]:
flat.index(min_lat)

1992

In [36]:
flat.count(min_lat)

1

In [37]:
flat[:3]

[-6.081689, -5.207083, -5.826789]

In [38]:
lat = to_float(get_attribute(data, 'latitude'))
lon = to_float(get_attribute(data, 'longitude'))
points = list(zip(lat, lon))
points[:3]

[(-6.081689, 145.391881), (-5.207083, 145.7887), (-5.826789, 144.295861)]

In [39]:
import math
def euclidean_distance(point1, point2):
    """
    Calculate Euclidean distance between to points
    
    d_{1,2} = sqrt(  (x1-x2)**2 + (y1-y2) **2   )
    
    Arguments
    ---------
    
    point1 : tuple
             (x1, y1, .....)
             
    point2 : tuple
             (x2, y2, .....)
    
    
    Return
    ------
    
    d_{1,2} : float
              Euclidean distance
    """
    x1, y1 = point1
    x2, y2 = point2
    
    dx = x1 - x2
    dy = y1 - y2
    
    return math.sqrt(dx*dx + dy*dy)

In [40]:
euclidean_distance( (0,0), (1,1))

1.4142135623730951

In [41]:
euclidean_distance(points[0], points[1])

0.9604170833533705

In [42]:
inf = float('inf')
ninf = float('-inf')

In [43]:
5 > ninf

True

In [44]:
-99999 > ninf

True

In [45]:
5 < inf

True

In [46]:
# find the nearest neighbor for an origin airport 
def nearest_airport(origin_airport, points):
    # don't calculate d_{i,i}
    nnd = inf
    closest_j = inf
    i = origin_airport
    for j, point in enumerate(points):
        d_ip = euclidean_distance(points[i], point)
        if d_ip != 0:
            if d_ip < nnd:
                nnd = d_ip
                closest_j = j
    return closest_j, nnd

In [47]:
nearest_airport(0, points)

(4901, 0.42477695483866257)

In [48]:
names = get_attribute(data, 'name')

In [49]:
names[4901]

'Chimbu Airport'

In [50]:
names[0]

'Goroka'

In [51]:
nearest_airport(4901, points)

(0, 0.42477695483866257)

# Functions as first class objects

In [52]:
def spam():
    print('Hi world')

In [53]:
spam()

Hi world

In [54]:
def do_twice(f):
    f()
    f()

In [55]:
do_twice(spam)

Hi world
Hi world